### ISSUE TITLE
ДЗ 5: Абстрактные методы

### ISSUE THREAD

**Issue by KayAltos9104** [Raltahook12/Lesson2#4]
Раз уж метод пустой, то лучше его абстрактным сделать, раз класс абстрактный:
```
public virtual void Fight(Character DamageDealer)
        {

        }
```

**Comment by Raltahook12** [comment]
Я думал он автоматически абстрактный

**Comment by KayAltos9104** [comment]
Нет, чтобы он был абстрактным его надо как abstract пометить))
